// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(APIDBContext))]
    [Migration("20191010173153_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.attribute", b =>
                {
                    b.Property<string>("attribute_code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("attribute_type");

                    b.Property<int?>("created_by_ID");

                    b.Property<DateTime?>("created_date");

                    b.Property<string>("description");

                    b.Property<string>("description_code");

                    b.Property<string>("entity_type");

                    b.Property<int?>("is_active");

                    b.Property<string>("is_required");

                    b.Property<string>("mask");

                    b.Property<int?>("min_width");

                    b.Property<string>("parent_attribute_code");

                    b.Property<string>("placeholder_code");

                    b.Property<string>("regular_expression");

                    b.Property<int>("sort_order");

                    b.Property<int?>("updated_by_ID");

                    b.Property<DateTime?>("updated_date");

                    b.HasKey("attribute_code");

                    b.ToTable("attribute");
                });

            modelBuilder.Entity("WebAPI.Models.attribute_value", b =>
                {
                    b.Property<string>("attribute_value_code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("attribute_code");

                    b.Property<int>("created_by_ID");

                    b.Property<DateTime>("created_date");

                    b.Property<string>("description");

                    b.Property<string>("description_code");

                    b.Property<string>("is_active");

                    b.Property<string>("parent_attribute_value_code");

                    b.Property<int>("updated_by_ID");

                    b.Property<DateTime>("updated_date");

                    b.HasKey("attribute_value_code");

                    b.ToTable("attribute_value");
                });
#pragma warning restore 612, 618
        }
    }
}
